- name: datatypes
  hosts: local
  connection: local
  vars:
    COURSE: "Devops with AWS" #string
    HOURS: 120  #int
    LIVE: true  #boolean
    DETAILS:  #list [ ]
    - AWS
    - AZURE
    - GCP
    TOOLS:   #map { }
    ci: jenkins
    cloud: AWS
    os: linux


  tasks:
    - name: print the datatypes
      ansible.builtin.debug:
        msg: " course is {{ COURSE }} Hours is {{ HOURS }} Live? {{ LIVE }} Details are {{ DETAILS }} Details {{ DETAILS }} "  