- name: conditions
  hosts: local
  connection: local
  vars_prompt:
    - name: number
      prompt: what is your number?
      private: false

  tasks:
    - name: print lessthan 100
      ansible.builtin.debug:
      msg: "{{ number }} is lessthan 100"
      when: number <= 100

    - name: print greaterthan 100
      ansible.builtin.debug:
        msg: "{{ number }} is greaterthan 100"
        when: number > 100