- name: install multiple applications
  hosts: local
  connection: local
  tasks: 
    - name: install multiple applications
      ansible.builtin.package:
          name: "{{ item }}"
          state: present

      loop:
      - gcc
      - git
      - zip      