- name: filters
  hosts: web
  become: yes
  vars_files:
    - project.yaml
  tasks:
    - name: print filters
      ansible.builtin.debug:
        msg: "{{ variable | default(5) }}"

    - name: print fruits
      vars:
        fruits: apple,banana,mango
      ansible.builtin.debug:
        msg: "{{ fruits | split(',') }}"    
